project_id = "zcrwmdctwjqrvzbvfpuj"

[functions.create-payment]
verify_jwt = true

[functions.generate-certificate]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.verify-mercadopago-payment]
verify_jwt = true

[functions.verify-certificate]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.generate-copy]
verify_jwt = true

[functions.generate-course-image]
verify_jwt = true

[functions.ai-chat]
verify_jwt = false
